version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  setup:
    docker:
      - image: circleci/node:12.13-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install

workflows:
  build:
    jobs:
      - setup
      - cypress/run:
          requires:
            - setup
          start: npm start
          record: true
          wait-on: 'http://localhost'
          post-steps:
            - run: 'npm run deploy'