version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          start: react-scripts start
          record: true
          wait-on: 'http://localhost:3000'
          post-steps:
            - run: 'npm run deploy'