version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  setup:
    docker:
      - image: circleci/node:12.13
    steps:
      - checkout
      - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
      - run: npm install
      - save_cahce:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  build:
    jobs:
      - setup
      - cypress/run:
          start: react-scripts start
          record: true
          wait-on: 'http://localhost:3000'
          post-steps:
            - run: 'npm run deploy'